# Generated by Django 4.2.5 on 2023-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
    ]
